name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "12", "10", "8"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --ignore-engines
      - run: yarn test
      - run: yarn build
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: e0dea8962d49b88cb184bc4dc460afb7caa9083c96a4647f22386c833c1f73b2
        with:
          coverageCommand: yarn coverage
